name: Build and test
on:
  push:
    branches: [main, develop]

  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os: [windows, macos, ubuntu]
        compiler: [gcc, clang, msvc]
        buildType: [Debug, Release]

        exclude:
        - os: windows
          compiler: gcc

        - os: ubuntu
          compiler: msvc

        - os: macos
          compiler: msvc

        - os: macos
          compiler: gcc

    env:
      BUILD_TYPE: ${{ matrix.buildType }}

      C_COMPILER: ${{ matrix.compiler }}
      CXX_COMPILER: ${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set Compiler (Windows)
      if: ${{ matrix.os == 'windows' }}
      run: |
        if ('${{ matrix.compiler }}' -ne 'msvc') {
          $env:CC = '${{ env.C_COMPILER }}'
          $env:CXX = '${{ env.CXX_COMPILER }}'
        }

    - name: Set Compiler (Linux/macOS)
      if: ${{ matrix.os != 'windows' }}
      run: |
        export CC=${{ env.C_COMPILER }}
        export CXX=${{ env.CXX_COMPILER }}

    - name: Configure
      run: cmake -B ${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{ matrix.compiler != 'msvc' && '-G Ninja' }}

    - name: Build
      run: cmake --build ${{runner.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ${{runner.workspace}}/build/bin/unit_test${{ matrix.os == 'windows' && '.exe' || '' }}

    - name: Create Artifact (Windows)
      if: ${{ matrix.os == 'windows' }}
      run: Copy-Item -Path "${{runner.workspace}}/build/bin/${{ matrix.buildType }}" -Destination "${{runner.workspace}}/build/artifact" -recurse -Force

    - name: Create Artifact (Linux/macOS)
      if: ${{ matrix.os != 'windows' }}
      run: cp -vr ${{runner.workspace}}/build/bin ${{runner.workspace}}/build/artifact

    - name: Publish Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.buildType == 'Release' && 'release' || 'debug' }}"
        path: ${{runner.workspace}}/build/artifact
